apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gw.fullname" . }}
  labels:
    {{- include "gw.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gw.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gw.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: local
              containerPort: 9902
              protocol: TCP
            - name: wx
              containerPort: 9903
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /__health
          #     port: local
          # readinessProbe:
          #   httpGet:
          #     path: /__health
          #     port: local
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: WXGATEWAY_SECRET
              value: "{{ .Values.secret }}"
            - name: WXGATEWAY_APPID
              value: "{{ .Values.appid }}"
            - name: WXGATEWAY_GW_ID
              value: "{{ .Values.gwid }}"
            - name: WXGATEWAY_DTYPE
              value: "K8s"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
