apiVersion: v1
kind: Service
metadata:
  name: {{ include "gw.fullname" . }}
  labels:
    {{- include "gw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.localport }}
      targetPort: local
      protocol: TCP
      name: local
    - port: {{ .Values.service.wxport }}
      targetPort: wx
      protocol: TCP
      name: wx
  selector:
    {{- include "gw.selectorLabels" . | nindent 4 }}
